### PR TITLE
Use bigarray-compat

### PR DESCRIPTION
**Pull request by TheLortex**
In the mirage dunification effort (mirage/mirage#969)

The goal of `bigarray-compat` is to use `Stdlib.Bigarray` when possible (>= 4.07) but fallback to `Bigarray`. This allows to avoid the `unix` dependency grabbed by `Bigarray` and helps for mirage builds. 

It's also possible to directly use `Stdlib.Bigarray` instead, if `< 4.07` compatibility is not necessary.

### CODE REVIEW

**Comment by XVilka** [comment]
Fails to compile on 4.02 and 4.03 versions:
```
#=== ERROR while compiling asn1-combinators.0.2.0 =============================#
# context     2.0.3 | linux/x86_64 | ocaml-base-compiler.4.04.2 | pinned(file:///home/travis/build/mirleft/ocaml-asn1-combinators)
# path        ~/.opam/ocaml-base-compiler.4.04.2/.opam-switch/build/asn1-combinators.0.2.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p asn1-combinators -j 1
# exit-code   1
# env-file    ~/.opam/log/asn1-combinators-25030-ffb3fd.env
# output-file ~/.opam/log/asn1-combinators-25030-ffb3fd.out
### output ###
#       ocamlc src/.asn1_combinators.objs/byte/asn_combinators.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/travis/.opam/ocaml-base-compiler.4.04.2/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.asn1_combinators.objs/byte -I src/.asn1_combinators.objs/public_cmi -I /home/travis/.opam/ocaml-base-compiler.4.04.2/lib/bigarray-compat -I /home/travis/.opam/ocaml-base-compiler.4.04.2/lib/cstruct -I /home/travis/.opam/ocaml-base-compiler.4.04.2/lib/ptime -I /home/travis/.opam/ocam[...]
# File "src/asn_combinators.ml", line 94, characters 16-34:
# Error: Unbound value M2.max_binding_opt
```

**Comment by TheLortex** [comment]
It fails the same way on master, this patch is unrelated

**Comment by XVilka** [comment]
Then there is no reason not to merge.

**Comment by TheLortex** [comment]
Why that ? It still fixes https://github.com/mirleft/ocaml-asn1-combinators/issues/28

**Comment by XVilka** [comment]
@TheLortex sorry, I used double negation, might be unclear.

**Comment by TheLortex** [comment]
Oh right, my bad ! We just need to wait for @pqwy's approval then.

**Comment by XVilka** [comment]
@pqwy @hannesm could you check this one please?

**Comment by XVilka** [comment]
Are there any updates?
